/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminAside: typeof import('./src/components/Admin/AdminAside.vue')['default']
    AdminMain: typeof import('./src/components/Admin/AdminMain.vue')['default']
    Aside: typeof import('./src/components/Home/Aside.vue')['default']
    CategoryMain: typeof import('./src/components/Admin/category/CategoryMain.vue')['default']
    Content: typeof import('./src/components/Home/Content.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./src/components/Home/Footer.vue')['default']
    Header: typeof import('./src/components/Home/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteMain: typeof import('./src/components/Admin/site/SiteMain.vue')['default']
    Statistic: typeof import('./src/components/Home/Statistic.vue')['default']
  }
}
